title: Student Services Digital
url: ""
favicon: /images/TP Icon copy.png
colors:
  primary-color: "#990000"
  secondary-color: "#ef0c1d"
  media-colors:
    - title: media-color-one
      color: "#000000"
    - title: media-color-two
      color: "#9b9b9b"
    - title: media-color-three
      color: "#e09f26"
    - title: media-color-four
      color: "#edd364"
    - title: media-color-five
      color: "#00838f"
resources_name: resource
description: "Access Student Services digitally anytime and anywhere at your fingertips! "
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d2wl6b84kga1ce.amplifyapp.com/
prod: https://master.d2wl6b84kga1ce.amplifyapp.com/
shareicon: /images/SSD_Banner05.png
is_government: false
